#!/usr/bin/env sh

docker run --rm -it \
    -e BUCKET_NAME=$BUCKET_NAME \
    -e CALENDARS_BUCKET_NAME=$CALENDARS_BUCKET_NAME \
    -e AWS_REGION=$AWS_REGION \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
    uv
